### ISSUE TITLE
Ability to set notification emails to only be sent once a week

### ISSUE THREAD

**Issue by jaydenelley** [silverstripe/silverstripe-contentreview#212] opened 2023-09-04 21:38 UTC
We have users that are assigned to a lot of pages and sometimes it can take some time for them to review content. Rather than bombarding them with a growing list of notifications everyday it would be great if we could set the notification emails to only be sent one day a week.

**Comment by GuySartorelli** [comment] 2023-09-06 00:03
I'm going to close this given there is no information at all in the issue description.

Please provide as much information as you can about this in the issue description and then `@` me in a new comment, and I'll take another look.

**Comment by GuySartorelli** [comment] 2023-09-06 01:23
Hi @jaydenelley,

Thank you for suggesting this.

As per [our documentation](https://docs.silverstripe.org/en/5/contributing/issues_and_bugs/#feature-requests) we don't typically accept feature requests as GitHub issues - but we make exceptions if the person raising the issue is willing to implement the requested feature.

This does sound like it could be a useful opt-in behaviour. Would you like to give a go at implementing it in a pull request?

**Comment by jaydenelley** [comment] 2023-09-06 01:36
Thanks @GuySartorelli I understand the issues process now but I have no idea how to implement this.

**Comment by GuySartorelli** [comment] 2023-09-06 01:37
Okay, fair enough. I'm going to close this issue for now then. If you figure it out or can find someone who's willing to implement the feature we can revisit it again at that time.
Cheers.

**Closed as not planned by GuySartorelli** 2023-09-06 01:37 UTC
Labels: impact/medium, type/enhancement, affects/v5
