### ISSUE TITLE
Reviewer log requires user to know their member ID number

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-contentreview#95] opened 2018-08-08 02:32 UTC
If you want to review a page, and mark the fact you've reviewed the page, you have to know your member id.

This doesn't make any sense, it should be populated by the current user who is logged in, or have a search field of some sort. 

![image](https://user-images.githubusercontent.com/67215/43812920-aec62064-9b17-11e8-80a8-d0f8993855e6.png)

**Comment by robbieaverill** [comment] 2018-08-08 02:33
Yeah agreed, this is a bug

**Comment by robbieaverill** [comment] 2018-08-14 02:32
Hey @torleif, just checking - which version of the contentreview module and cms/framework are you using?

I can't reproduce this problem using framework/cms 3.7.1 and contentreview 3.0.x-dev

![image](https://user-images.githubusercontent.com/5170590/44068584-dee57c3e-9fce-11e8-8904-bdf1d1384a9f.png)

**Comment by torleif** [comment] 2018-08-14 03:44
I'm using the stable version of the content review module "silverstripe/contentreview": "^3.0", not the dev version. I'm on framework 3.4

**Comment by robbieaverill** [comment] 2018-08-14 03:45
Can you please run `composer show` and paste in the specific version you have installed for content review and for framework? I'll try and reproduce

**Comment by robbieaverill** [comment] 2018-08-14 03:56
![image](https://user-images.githubusercontent.com/5170590/44070922-96facb34-9fda-11e8-9e62-14078a5c796b.png)

Fresh install with silverstripe/cms 3.4.6 and contentreview 3.0.8

**Comment by torleif** [comment] 2018-08-15 01:30
@robbieaverill it's a similar problem as #92. I deleted all members in my local dev DB apart from 10, and it turns into a dropdown listing the remaining members. 

it seems either the framework is changing the dropdown to a inputfield. the html is outputed as an input when it hits a low number

**Comment by robbieaverill** [comment] 2018-08-15 01:41
@torleif ah, right! You're experiencing this core behaviour:

https://github.com/silverstripe/silverstripe-framework/blob/3/model/fieldtypes/ForeignKey.php#L41-L48

This has been changed to be configurable in SilverStripe 4 rather than a hard coded threshold:

https://github.com/silverstripe/silverstripe-framework/blob/4/src/ORM/FieldType/DBForeignKey.php#L74-L83

In light of this, I'm going to close this issue since it's expected behaviour from the framework. In the case where you have a larger number of members than this threshold, you can always explicitly tell ContentReviewLog to scaffold a DropdownField by using a DataExtension on it:

```php
public function updateCMSFields(FieldList $fields)
{
    // Always scaffold a DropdownField, rather than using the default decision to change it to a NumericField
    // on larger member lists
    $fields->addFieldToTab('Root.Main', DropdownField('Reviewer', null, Member::get()->map('ID', 'Name'));
}
```

Note that this would be overriding the change here which was for performance reasons, so it could slow down your CMS a little.

Thanks for taking the time to log this issue, and the patience for working through it with me =)

**Closed by robbieaverill** 2018-08-15 01:41 UTC
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/UX, type/bug
